factors = [x_factors.tolist()] * 48 + [x_factors.tolist()] * 24 + [x_factors.tolist()]
win_type = [['full_apply', 'rolling']] * 48 + [['rolling']] * 24 + [['pct', 'full_apply']]  # [['switchblade']]
win_kwgs = [[{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': linreg_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': mean_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': median_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': relative_q, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': linreg_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': mean_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': median_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': relative_q, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': linreg_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': mean_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': median_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': relative_q, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_3shock_relative_6, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_3shock_relative_12, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_resid}, {'win_func': None, 'agg_func': ewm_6shock_relative_12, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': linreg_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': mean_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': median_relative, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': relative_q, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 3}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': linreg_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': mean_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': median_relative, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': relative_q, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 6}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': linreg_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': mean_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': median_relative, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': relative_q, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_3shock_relative_6, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_3shock_relative_12, 'window': 12}],
            [{'func': seasonal_remove_mstl_get_seasonal_trend}, {'win_func': None, 'agg_func': ewm_6shock_relative_12, 'window': 12}],
            [{'win_func': None, 'agg_func': linreg_relative, 'window': 3}],
            [{'win_func': None, 'agg_func': mean_relative, 'window': 3}],
            [{'win_func': None, 'agg_func': median_relative, 'window': 3}],
            [{'win_func': None, 'agg_func': relative_q, 'window': 3}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 3}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 3}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 3}],
            [{'win_func': None, 'agg_func': linreg_relative, 'window': 6}],
            [{'win_func': None, 'agg_func': mean_relative, 'window': 6}],
            [{'win_func': None, 'agg_func': median_relative, 'window': 6}],
            [{'win_func': None, 'agg_func': relative_q, 'window': 6}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 6}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 6}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 6}],
            [{'win_func': None, 'agg_func': linreg_relative, 'window': 12}],
            [{'win_func': None, 'agg_func': mean_relative, 'window': 12}],
            [{'win_func': None, 'agg_func': median_relative, 'window': 12}],
            [{'win_func': None, 'agg_func': relative_q, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_3, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_6, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_1shock_relative_12, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_3shock_relative_6, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_3shock_relative_12, 'window': 12}],
            [{'win_func': None, 'agg_func': ewm_6shock_relative_12, 'window': 12}],
#             [{'win_func': None, 'agg_func': switchmean, 'window': 3+1}]]
            [{}, {'func': binners_perc}]]
_ = f.represent(factors=factors, win_type_s=win_type, win_kwgs_s=win_kwgs)
